### ISSUE TITLE
Include a Code Theme by Default

### ISSUE THREAD

**Issue by chase** [segment-boneyard/socrates#15]
It seems that Socrates already puts code blocks through Rainbow's syntax highlighting, but all the work Rainbow does isn't visible without a theme.

If there is an issue with the currently available themes not matching the minimalist styling of Socrates, [Highlight.js](/isagalaev/highlight.js) is a great alternative to Rainbow.

**Comment by ianstormtaylor** [comment]
Believe it or not, there's a theme on there, but it's definitely subtle :p

Comments are slightly lighter and interesting things are slightly bluer. http://socrates.io/#PyHuL2z It also takes a while to kick in on longer documents.

**Comment by chase** [comment]
Thanks for the quick reply!

I guess I was just inpatient when trying out some fairly long source code snippets.
