### ISSUE TITLE
Add tooltips to UI buttons

### ISSUE THREAD

**Issue by yefremov** [segment-boneyard/socrates#18]
UI buttons does not have any short description on them, you must push to see what they do. It is good practice for UX to see some delayed description when hover on UI buttons even if the icon looks descriptive. Simple HTML `title` attribute should be enough.

**Comment by jangxyz** [comment]
+1 as I've thought the same thing. Made a pull request at #19

**Comment by yefremov** [comment]
Fixed in #19.
