### ISSUE TITLE
Undo / CTRL+Z (Chrome)

### ISSUE THREAD

**Issue by davetransom** [segment-boneyard/socrates#2]
Just saw this mentioned by Smashing Magazine (https://twitter.com/smashingmag/status/268462875205566464) and is looks **very nice**.

Editing the sample at http://socrates.io, I immediately deleted some text, made changes, then wanted to undo - but alas, it didn't work (Google Chrome 22.0.1229.96 m). 

It's pretty fundamental to text-editing. Any plans to support CTRL+Z?

**Comment by ianstormtaylor** [comment]
Glad you like it :)

I think the `ctrl-z` problem is actually a webkit bug. It works fine in Firefox, and there a similar bugs filed: http://code.google.com/p/chromium/issues/detail?id=48412

**Comment by davetransom** [comment]
Ahh, shame. Is it only failing due to the textarea being updated by javascript then?

**Comment by ianstormtaylor** [comment]
Ah, yup it does depend on Javascript, so that could be it
