### ISSUE TITLE
what you forgot about, was math.

### ISSUE THREAD

**Issue by ianstormtaylor** [segment-boneyard/socrates#20]
any two $ in a document make everything between them math

**Comment by gniezen** [comment]
How difficult will it be to add support for inline math?

**Comment by ianstormtaylor** [comment]
It's already there :)

Using MathJax: http://www.mathjax.org/

Just wrap your math in double dollar signs: `$$`

**Comment by gniezen** [comment]
I've been playing around with it all afternoon, and it works great. What I want is [in-line](http://docs.mathjax.org/en/v1.1-latest/start.html#tex-and-latex-input) math, using single dollar signs or `\(...\)` to have equations on the same line as the text.

**Comment by ianstormtaylor** [comment]
Ah I see. Not sure, /cc @reinpk

**Comment by reinpk** [comment]
Ah, yeah this has been bugging me too. I'll add support for inline soon~

**Comment by gniezen** [comment]
Excellent, thanks guys! When will this be available on socrates.io, or is that only meant to be a demo server? (I've been bookmarking documents created using socrates.io)

**Comment by ianstormtaylor** [comment]
It's live! I've changed the syntax for inline to `$$` and for block to `$$$`. Didn't want to use single dollar signs since those could easily crop up in normal text.
