### ISSUE TITLE
start editing?

### ISSUE THREAD

**Issue by dominictarr** [segment-boneyard/socrates#3]
I can't figure out how to edit, yet the introduction I read said I simply edited text "on the left" 
(I can't find this page again - the link takes me someplace else now, to a poem by Beverly Dingus)

**Comment by ivolo** [comment]
Hi Dominic, Beverly Dingus is by design :) 

You can't type in the left side text area? Which browser / environment?

**Comment by ianstormtaylor** [comment]
Just to be clear, the Beverly Dingus poem is just filler text for every new pad when you go to the homepage. (After the first time when it was the directions).

But yeah let us know which browser you're using. The left side of the page should just be an editable textarea

cheers

**Comment by dominictarr** [comment]
chrome on linux.

**Comment by dominictarr** [comment]
I don't see a textarea.

**Comment by ianstormtaylor** [comment]
It's not exactly styled like a textarea, but the entire left side of the page should be editable. Hopefully that makes sense, leme know if not

**Comment by dominictarr** [comment]
Okay, this works in FF but not in chrome.
I managed to see the edit field when I opened the developer console, but otherwise, 
this just seems like a problem with width etc...
