### ISSUE TITLE
All Saved pages are gone - Database gone?

### ISSUE THREAD

**Issue by diek** [segment-boneyard/socrates#36]
I have been using socrates.io for several years, and of course today is the day. All is gone. Was this intentional or a glitch that will be repaired?

**Comment by EpokK** [comment]
Same thing on my side, I hope the problem can be repaired.

**Comment by ivolo** [comment]
hey @diek and @EpokK — this is a bummer, thanks for bringing it up (and excited to learn that people use Socrates!) As you know its been a side project, and i'm focused day to day on Segment. I've just sent an email to Firebase support and will let you know what I hear back.

**Comment by diek** [comment]
@ivolo  thank god someone responded. My friends and I love it, and I am sure if more people knew about it, it would get a lot more usage.

**Comment by diek** [comment]
Database is back! Thanks @ivolo !
