### ISSUE TITLE
Printable View

### ISSUE THREAD

**Issue by chid** [segment-boneyard/socrates#4]
I think there needs to be a printable view enabled.

It can be either done with CSS or having a button that converts the document into a printable view (ie. hides the left pane)

**Comment by ianstormtaylor** [comment]
Ilya just ran into this problem yesterday :) it's definitely on our list of additions! Thanks

**Comment by SimplGy** [comment]
Made a print stylesheet, tested briefly, and added a pull request. Hopefully it'll get in soon :)

**Comment by ianstormtaylor** [comment]
done now! thanks :)
