### ISSUE TITLE
Uploading to S3

### ISSUE THREAD

**Issue by duezerouno** [segment-boneyard/socrates#8]
I am trying to put it up on s3. I am getting an error in app-model.js

```
   Document : function (body) {
    window.analytics.track('Create New Document');

    Uncaught TypeError: Cannot call method 'track' of undefined

    return this.fetchDocument(this.generateDocumentId(), body);
},
```

So it wont me create new posts. 

You can check it at: http://cabrillo.s3-website-us-east-1.amazonaws.com/

**Comment by ianstormtaylor** [comment]
We use our own [Segment.io](https://segment.io) account to initialize analytics on Socrates, so I think the error is coming from that. Either you'll need to remove the analytics calls, or use your own account instead.
